version: '2.1'

services:
  kenyaemr-demo-mysql:
    restart: "always"
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-test}
      MYSQL_USER: ${MYSQL_USER:-test}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test}
      TZ: "Africa/Nairobi"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql # Mount the dump.sql into the container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  kenyaemr-demo:
    restart: "always"
    image: tomcat:9-jre8-openjdk
    depends_on:
      kenyaemr-demo-mysql:
        condition: service_healthy
    ports:
      - "8500:8443"
      - "8501:8080"
    environment:
      DB_DATABASE: ${MYSQL_DB:-openmrs}
      DB_HOST: kenyaemr-demo-mysql
      DB_USERNAME: ${MYSQL_USER:-test}
      DB_PASSWORD: ${MYSQL_PASSWORD:-test}
      DB_CREATE_TABLES: 'true'
      DB_AUTO_UPDATE: 'true'
      MODULE_WEB_ADMIN: 'true'
      TZ: "Africa/Nairobi"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/openmrs/"]
      timeout: 20s
